### ISSUE TITLE
CrashlyticsLogWriter is ignoring `minSeverity`

### ISSUE THREAD

**Issue by Nek-12** [touchlab/Kermit#431]
The image pretty much sums it up. Our crashlytics logs are polluted by `verbose`-level garbage and leak sensitive data. 

![Image](https://github.com/user-attachments/assets/bc14f103-f44c-4eef-9fd3-be788c80c3ea)

**Comment by KevinSchildhorn** [comment]
Hi Nikita, Are you opening the project from the root directory?

![Image](https://github.com/user-attachments/assets/4a211605-a5c2-49fa-ad16-6f1c11b5370e)

`isLoggable` is used in the [BaseLogger](https://github.com/touchlab/Kermit/blob/5bb621258d4ae0c2fdd6e13bda62b54045e78821/kermit-core/src/commonMain/kotlin/co/touchlab/kermit/BaseLogger.kt#L71) which is in the `kermit-core` module, so if you don't open it from the root then it won't see that module.

I'm not sure why you're seeing `verbose` messages, can you confirm your `minSeverity` passed into your [CrashlyticsLogWriter](https://github.com/touchlab/Kermit/blob/5bb621258d4ae0c2fdd6e13bda62b54045e78821/extensions/kermit-crashlytics/src/commonMain/kotlin/co/touchlab/kermit/crashlytics/CrashlyticsLogWriter.kt#L26) and your `minSeverity` passed into your [Logger](https://github.com/touchlab/Kermit/blob/5bb621258d4ae0c2fdd6e13bda62b54045e78821/kermit/src/commonMain/kotlin/co/touchlab/kermit/Logger.kt#L24)?

I made a quick [branch](https://github.com/touchlab/Kermit/blob/ks/AddingCrashlyticsTests/extensions/kermit-crashlytics/src/commonTest/kotlin/co/touchlab/kermit/crashlytics/CrashlyticsLogWriterTest.kt) that runs some tests on `CrashlyticsLogWriter` that seem to work fine. If you're still running into issues let me know.

**Comment by Nek-12** [comment]
Yes, I'm sorry for the confusion. isLoggable is used indeed, however I can confirm that we are seeing Verbose-level logs in our crashlytics console. Small example (to not leak too much data)

<img width="1055" alt="Image" src="https://github.com/user-attachments/assets/725348c9-c6e8-4bf8-957c-a13a36fd5b6c" />

Yes I passed minSeverity = Info and minCrashSeverity = Error.

I'm only setting the Severity and loggers once per app lifecycle. What else could be the case of that behavior?

**Comment by KevinSchildhorn** [comment]
That should be enough yes. I'm not sure why this isn't working as expected for you, I'm trying to test it on my side and it seems correct. Can you share the code of how you're setting up and logging to the `Logger`? Can you also try just creating a custom logger in your project as a test and seeing if the issue still occurs? Something like:

```
val logger = Logger(
    config = loggerConfigInit(CrashlyticsLogWriter()),
    tag = "MyAppTag"
)
logger.v { "Hello World" }
```

Also make sure you're using the latest version of kermit (2.0.5).

If that still doesn't work then maybe you can create a local copy of [CrashlyticsLogWriter](https://github.com/touchlab/Kermit/blob/5bb621258d4ae0c2fdd6e13bda62b54045e78821/extensions/kermit-crashlytics/src/commonMain/kotlin/co/touchlab/kermit/crashlytics/CrashlyticsLogWriter.kt#L26) so that you can breakpoint and test there, since `LogWriter` is open.

Let me know if that helps and if you're still seeing the issues there.

**Comment by samhill303** [comment]
Sounds like this is resolved. Closing

**Comment by Nek-12** [comment]
This isn't resolved. We just haven’t yet had a public release that would let us test if the logging spam is reduced. I’ll get back in touch in a week or so

**Comment by samhill303** [comment]
@Nek-12 Are you still having any issues?
